AppBundle\Entity\Activity:
    type: entity
    table: Activity
    indexes:
        fkActivityPhaseId_idx:
            columns:
                - phaseId
        fkActiviyResponsibleUserId_idx:
            columns:
                - responsibleUser
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        ismilestone:
            type: boolean
            nullable: true
            column: isMilestone
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        startdate:
            type: date
            nullable: true
            column: startDate
        enddate:
            type: date
            nullable: true
            column: endDate
        created:
            type: datetime
            nullable: true
        modified:
            type: datetime
            nullable: true
        deleted:
            type: datetime
            nullable: true
        actualstartdate:
            type: date
            nullable: true
            column: actualStartDate
        actualenddate:
            type: date
            nullable: true
            column: actualEndDate
    manyToOne:
        phaseid:
            targetEntity: Phase
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                phaseId:
                    referencedColumnName: id
            orphanRemoval: false
        responsibleuser:
            targetEntity: Employee
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                responsibleUser:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
