AppBundle\Entity\Employee:
    type: entity
    table: Employee
    indexes:
        fkEmployeeRoleId_idx:
            columns:
                - roleId
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstname:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        lastname:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        created:
            type: datetime
            nullable: true
        modified:
            type: datetime
            nullable: true
        deleted:
            type: datetime
            nullable: true
    manyToOne:
        roleid:
            targetEntity: Role
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                roleId:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
