AppBundle\Entity\File:
    type: entity
    table: File
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        uri:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        created:
            type: datetime
            nullable: true
        modified:
            type: datetime
            nullable: true
        deleted:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
