AppBundle\Entity\Financialresource:
    type: entity
    table: FinancialResource
    indexes:
        fkFinancialResourceActivity_idx:
            columns:
                - activityId
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        typeid:
            type: integer
            nullable: true
            options:
                unsigned: true
            column: typeId
        plannedcost:
            type: decimal
            nullable: true
            precision: 10
            scale: 0
            column: plannedCost
        actualcost:
            type: decimal
            nullable: true
            precision: 10
            scale: 0
            column: actualCost
        created:
            type: datetime
            nullable: true
        modified:
            type: datetime
            nullable: true
        deleted:
            type: datetime
            nullable: true
    manyToOne:
        activityid:
            targetEntity: Activity
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                activityId:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
